## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file report.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_40 = Integer(40); _sage_const_111p939167 = RealNumber('111.939167'); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_12 = Integer(12); _sage_const_1527p764697 = RealNumber('1527.764697'); _sage_const_35p870348 = RealNumber('35.870348'); _sage_const_1 = Integer(1); _sage_const_5p827224 = RealNumber('5.827224'); _sage_const_1p768803 = RealNumber('1.768803'); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_484p906122 = RealNumber('484.906122'); _sage_const_30 = Integer(30); _sage_const_0p341143 = RealNumber('0.341143'); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50)## This file (report.sagetex.sage) was *autogenerated* from report.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('report', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 list=((_sage_const_5 ,_sage_const_0p341143 ),(
 _sage_const_10 ,_sage_const_1p768803 ),
 (_sage_const_15 ,_sage_const_5p827224 ),(
 _sage_const_20 ,_sage_const_35p870348 ),(
 _sage_const_30  ,_sage_const_111p939167 ),(
 _sage_const_40  ,_sage_const_484p906122 ),(
 _sage_const_50 ,_sage_const_1527p764697 ))
 r = [(list[i][_sage_const_0 ],list[i][_sage_const_1 ]) for i in range(_sage_const_7 )]
 p=list_plot(r,color='red',plotjoined=True,marker=".",frame=True,axes_labels=['$Number \ Of \ Storeys$ axis','$Time(sec)$ axis'],axes=False)
except:
 _st_.goboom(_sage_const_11 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='png', _p_=p)
except:
 _st_.goboom(_sage_const_12 )
_st_.endofdoc()
