## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file chapter12-1.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_107 = Integer(107); _sage_const_111 = Integer(111); _sage_const_110 = Integer(110); _sage_const_81 = Integer(81); _sage_const_82 = Integer(82); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_56 = Integer(56); _sage_const_18 = Integer(18); _sage_const_53 = Integer(53); _sage_const_50 = Integer(50); _sage_const_108 = Integer(108); _sage_const_74 = Integer(74); _sage_const_77 = Integer(77); _sage_const_92 = Integer(92); _sage_const_90 = Integer(90); _sage_const_104 = Integer(104); _sage_const_96 = Integer(96); _sage_const_94 = Integer(94)## This file (chapter12-1.sagetex.sage) was *autogenerated* from chapter12-1.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('chapter12-1', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
     p,q=var('p','q')
except:
 _st_.goboom(_sage_const_50 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(p/q))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.inline(_sage_const_1 , latex(q))
except:
 _st_.goboom(_sage_const_56 )
try:
 _st_.inline(_sage_const_2 , latex(p))
except:
 _st_.goboom(_sage_const_56 )
_st_.blockbegin()
try:
     a,t_v,Vu,b_0,d=var('a','t_v','Vu','b_0','d')
     P,p,Sp=var('P','p','Sp')
     f_ck,t_a,t_c,k_s=var('f_ck','t_c','t_a','k_s')
except:
 _st_.goboom(_sage_const_74 )
_st_.blockend()
try:
 _st_.inline(_sage_const_3 , latex(a))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.inline(_sage_const_4 , latex(t_v))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.inline(_sage_const_5 , latex(t_v))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.inline(_sage_const_6 , latex(Vu/(b_0*d)))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.inline(_sage_const_7 , latex(_sage_const_1p5 *Sp/(_sage_const_4 *(a+d)*d)))
except:
 _st_.goboom(_sage_const_82 )
_st_.blockbegin()
try:
     b=var('b')
     Sp=P-p*(a + d)*_sage_const_2 
except:
 _st_.goboom(_sage_const_90 )
_st_.blockend()
try:
 _st_.inline(_sage_const_8 , latex(Sp))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.inline(_sage_const_9 , latex(b_0))
except:
 _st_.goboom(_sage_const_94 )
try:
 _st_.inline(_sage_const_10 , latex(t_a))
except:
 _st_.goboom(_sage_const_96 )
_st_.blockbegin()
try:
     t_c=k_s*_sage_const_0p25 *sqrt(f_ck)
except:
 _st_.goboom(_sage_const_104 )
_st_.blockend()
try:
 _st_.inline(_sage_const_11 , latex(t_a))
except:
 _st_.goboom(_sage_const_107 )
try:
 _st_.inline(_sage_const_12 , latex(k_s))
except:
 _st_.goboom(_sage_const_107 )
try:
 _st_.inline(_sage_const_13 , latex(t_c))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.inline(_sage_const_14 , latex(f_ck))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.inline(_sage_const_15 , latex(k_s))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.inline(_sage_const_16 , latex(b/a))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.inline(_sage_const_17 , latex(t_v))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.inline(_sage_const_18 , latex(t_a))
except:
 _st_.goboom(_sage_const_111 )
_st_.endofdoc()
