## -*- encoding: utf-8 -*-
## This file (chapter12-1.sagetex.sage) was *autogenerated* from chapter12-1.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('chapter12-1', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
     p,q=var('q','p')
except:
 _st_.goboom(50)
_st_.blockend()
try:
 _st_.inline(0, latex(p/q))
except:
 _st_.goboom(52)
_st_.endofdoc()
