## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file chapter12-1.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_0 = Integer(0); _sage_const_52 = Integer(52); _sage_const_50 = Integer(50)## This file (chapter12-1.sagetex.sage) was *autogenerated* from chapter12-1.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('chapter12-1', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
     p,q=var('q','p')
except:
 _st_.goboom(_sage_const_50 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(p/q))
except:
 _st_.goboom(_sage_const_52 )
_st_.endofdoc()
